export const API = 'API';
export const ADD_PROJECT_CREATOR = "ADD_PROJECT_CREATOR";


export const ADD_PROJECT_INFO = "ADD_PROJECT_INFO";
export const ADD_PROJECT_ID = "ADD_PROJECT_ID";
export const START_ADD_PROJECT_INFO = "START_ADD_PROJECT_INFO";
export const ADD_PROJECT_INFO_SUCSSES = "ADD_PROJECT_INFO_SUCSSES";
export const ADD_PROJECT_INFO_FAILS = "ADD_PROJECT_INFO_FAILS";

export const START_ADD_PROJECT_CONTENT = "START_ADD_PROJECT_CONTENT";
export const ADD_PROJECT_CONTENT_SUCSSES = "ADD_PROJECT_CONTENT_SUCSSES";
export const ADD_PROJECT_CONTENT_FAILS = "ADD_PROJECT_CONTENT_FAILS";


export const ADD_PROJECT_STEPS = "ADD_PROJECT_STEPS";
export const ADD_PROJECT_DESIGNERS = "ADD_PROJECT_DESIGNERS";
export const ADD_PROJECT_SUPPLIERS = "ADD_PROJECT_SUPPLIERS";
export const ADD_PROJECT_COVER = "ADD_PROJECT_SUPPLIERS";


export const START_ADD_PROJECT_ROLE = "START_ADD_PROJECT_ROLE";
export const ADD_PROJECT_ROLE_SUCSSES = "ADD_PROJECT_ROLE_SUCSSES";
export const ADD_PROJECT_ROLE_FAILS = "ADD_PROJECT_ROLE_FAILS";


export const START_ADD_PROJECT_COVER = "START_ADD_PROJECT_COVER";
export const ADD_PROJECT_COVER_SUCSSES = "ADD_PROJECT_COVER_SUCSSES";
export const ADD_PROJECT_COVER_FAILS = "ADD_PROJECT_COVER_FAILS";